/*Copyright (c) 2015-2016 mobeteq-com All Rights Reserved.
 This software is the confidential and proprietary information of mobeteq-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with mobeteq-com*/
package com.salesdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class TotalLeadsResponse implements Serializable {


    @ColumnAlias("LEADSCOUNT")
    private BigInteger leadscount;

    public BigInteger getLeadscount() {
        return this.leadscount;
    }

    public void setLeadscount(BigInteger leadscount) {
        this.leadscount = leadscount;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TotalLeadsResponse)) return false;
        final TotalLeadsResponse totalLeadsResponse = (TotalLeadsResponse) o;
        return Objects.equals(getLeadscount(), totalLeadsResponse.getLeadscount());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getLeadscount());
    }
}
